import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/lib/language";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LanguageProvider>
          {children}
          <footer className="site-footer">
            <div className="site-footer-inner">
              <div>
                <p className="site-footer-brand">InnovateHub</p>
                <p className="site-footer-copy">Connecting citizens, universities, industry, and government to solve real community challenges.</p>
              </div>
              <div className="site-footer-links">
                <a href="/success-stories">Success stories</a>
                <a href="/login">Account access</a>
              </div>
              <p className="site-footer-meta">(c) 2026 InnovateHub</p>
            </div>
          </footer>
        </LanguageProvider>
      </body>
    </html>
  );
}
